### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by ikanakova** [mmazzarolo/breathly-app#111]
Will the new version be available on F-Droid? There is still a version 1.9 on F-Droid.

**Comment by mmazzarolo** [comment]
Hey! I don't see why not. That said, I'm not managing the F-Droid version, so someone else should jump in and update it (I guess?).

**Comment by ikanakova** [comment]
I don't know, but perhaps @IzzySoft could advise.

**Comment by IzzySoft** [comment]
```yaml
UpdateCheckMode: Tags ^android-\d\.\d$
```

Proper tag names might help, no? :wink: Check when that pattern matched last (hint: `android-1.9`), and what the tag names are now (`android-2.0-(3145745)`). Since you've appended `-(\d)` at the end, updates could no longer be found by the updater.

**Comment by mmazzarolo** [comment]
Additionally, @ikanakova , besides the new tag format the build step might be different now since I'm using [Expo](https://expo.dev).

**Comment by ikanakova** [comment]
@mmazzarolo Does that mean the new version won't be on the F-Droid?

**Comment by mmazzarolo** [comment]
Hey @ikanakova [I didn't create](https://github.com/mmazzarolo/breathly-app/issues/7) and I never updated the F-Droid version of Breathly... I'm not even familiar with F-Droid and unfortunately I don't have much free time lately to investigate/learn how to update and support the new version :/ 
However, if anyone is willing to give it a try and see how to support the new Expo build (besides updating the tag pattern) and just need my permissions to update the release flow I'm happy to help you with that (as long as you already know the changes we need to make).

**Comment by IzzySoft** [comment]
@mmazzarolo if you want I can adjust the UpdateCheckMode mentioned above at F-Droid (disclosure: I'm one of the maintainers there) and we can see if the build succeeds once the updater has picked up the new release. We'd just need to remove the trailing `$` so the RegEx allows for "anything else following". We'd only need to keep the `android-` prefix to make sure the correct tags are matched.

**Comment by mmazzarolo** [comment]
@IzzySoft that works for me, thank you

**Comment by IzzySoft** [comment]
OK, [there you go](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12791) – and fingers crossed!

**Comment by IzzySoft** [comment]
Hm. I've no idea why it insists on v1.9 being the latest release – stripped UCM down to `^android-.+` now which should really match `android-2.1-(3145747)`…

**Comment by licaon-kter** [comment]
Did you rewrite the app in Expo? The recipe needs a complete overhaul then...

**Comment by mmazzarolo** [comment]
> Did you rewrite the app in Expo? The recipe needs a complete overhaul then...

[Yes](https://github.com/mmazzarolo/breathly-app/blob/master/DEVLOG.md#2023-02-04).

**Comment by IzzySoft** [comment]
Thanks @licaon-kter – and yes, see above…

**Comment by licaon-kter** [comment]
@mmazzarolo help?

Updated recipe: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12791/diffs?commit_id=fb2d997a907effcf86057090cd8818bc79828d51

But fails later: 
[com.mmazzarolo.breathly_3145747.log.gz](https://github.com/mmazzarolo/breathly-app/files/11758705/com.mmazzarolo.breathly_3145747.log.gz)


Where are the build instructions exactly?

**Comment by licaon-kter** [comment]
```
...
warning: the transform cache was reset.
                Welcome to Metro v0.72.4
              Fast - Scalable - Integrated


error index.js: [BABEL]: Cannot find module 'tailwindcss/lib/util/resolveConfigPath'
Require stack:
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/nativewind/dist/babel/index.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/nativewind/babel.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/@babel/core/lib/config/files/module-types.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/@babel/core/lib/config/files/configuration.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/@babel/core/lib/config/files/index.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/@babel/core/lib/index.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/metro-transform-worker/src/index.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/metro/src/DeltaBundler/Worker.flow.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/metro/src/DeltaBundler/Worker.js
Error: [BABEL]: Cannot find module 'tailwindcss/lib/util/resolveConfigPath'
Require stack:
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/jest-worker/build/workers/processChild.js (While processing: /home/v
agrant/build/com.mmazzarolo.breathly/node_modules/nativewind/babel.js).
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/nativewind/dist/babel/index.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/nativewind/babel.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/@babel/core/lib/config/files/module-types.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/@babel/core/lib/config/files/configuration.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/@babel/core/lib/config/files/index.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/@babel/core/lib/index.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/metro-transform-worker/src/index.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/metro/src/DeltaBundler/Worker.flow.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/metro/src/DeltaBundler/Worker.js
- /home/vagrant/build/com.mmazzarolo.breathly/node_modules/jest-worker/build/workers/processChild.js (While processing: /home/vagrant/build/com.mmazzarolo.breathly/node_modules/nativewind/babel.js)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/vagrant/build/com.mmazzarolo.breathly/node_modules/nativewind/dist/babel/index.js:9:45)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/vagrant/build/com.mmazzarolo.breathly/node_modules/nativewind/babel.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build completed with 2 failures.
```
